# -*- coding: utf-8 -*-
"""week 4 Assignment

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Z6Jt1CwYyVZG4ude8Vs3-AbfKEj-2j_u

**Week 4 Assignment — Functions**

Question 1 — Small Shop Billing and Inventory System
A small grocery shop in Kathmandu wants to automate its billing counter.
When a customer places an order, the program should calculate the total bill
and update the remaining stock. If a customer asks for more than what is in
stock, the program should skip that item and notify the shopkeeper.
"""

#Prashant Puri

inventory = {
    "rice":  {"price": 120, "stock": 20},
    "milk":  {"price": 90,  "stock": 10},
    "bread": {"price": 60,  "stock": 15},
    "eggs":  {"price": 15,  "stock": 30},
}

cart = {
    "rice": 2,
    "milk": 3,
    "eggs": 12,
}

def process_order(inventory, cart):
    bill_items = {}
    grand_total = 0

    for item, qty in cart.items():
        if item not in inventory:
            print(f"Sorry, '{item}' is not available in the shop.")
            continue

        stock = inventory[item]["stock"]
        price = inventory[item]["price"]

        if qty > stock:
            print(f"Sorry, not enough stock for {item}")
        else:
            item_total = price * qty
            bill_items[item] = (qty, item_total)
            grand_total += item_total
            inventory[item]["stock"] -= qty

    print("\n---- Here is the bill ----")
    for item, (qty, total) in bill_items.items():
        print(f"{item} x{qty} = NPR {total}")
    print(f"Grand Total: NPR {grand_total}")
    print("--------------")
    print("--------------")

    updated = ", ".join(
        f"{item}={info['stock']}" for item, info in inventory.items()
    )
    print(f"The updated stock are : {updated}\n")


process_order(inventory, cart)

"""Question 2 — Water Level Alert System (Koshi River)
After heavy monsoon rains, the Koshi River in eastern Nepal often floods
nearby villages.The government has placed water-level sensors along the
river. You are helping the Department of Hydrology write a simple program
that reads each sensor's water level and tells field workers whether they need
to act.
"""

#Prashant Puri

sensors = [
    ("Chatara",          2.8),
    ("Tribeni Ghat",     5.4),
    ("Koshi Barrage",    4.1),
    ("Sunsari Bridge",   1.9),
    ("Saptakoshi Camp",  6.0),
]

def check_water_level(location, level_metres):
    if level_metres < 3:
        return "Safe"
    elif level_metres <= 5:
        return "Warning — Alert the  nearby villages"
    else:
        return "DANGER — People need to evacuate immediately!"

print("=== Koshi River Water Level Report ===")
for location, level in sensors:
    status = check_water_level(location, level)
    print(f"{location} ({level} m): {status}")
print()

"""Question 3 — Date Converter for Nepal Bank System (BS ↔ AD)
A bank in Nepal stores customer dates in both Bikram Sambat (BS) and
Gregorian (AD) calendars — citizenship cards come in BS, but the core
banking software uses AD. Staff need a function that converts between the
two and formats the result depending on where it will be used.
"""

#Prashant Puri
bs_months = [
    "Baisakh", "Jestha", "Ashadh", "Shrawan", "Bhadra", "Ashwin",
    "Kartik",  "Mangsir", "Poush", "Magh",    "Falgun", "Chaitra"
]

def ordinal(n):
    """Return day number with ordinal suffix: 1 → 1st, 2 → 2nd, etc."""
    if 11 <= n % 100 <= 13:
        return f"{n}th"
    return f"{n}{['th','st','nd','rd','th'][min(n % 10, 4)]}"

def convert_date(date_str, from_cal, to_cal, style="iso"):
    year, month, day = map(int, date_str.split("-"))


    if from_cal == to_cal:
        converted_year = year
    elif from_cal == "AD" and to_cal == "BS":
        converted_year = year + 56
    elif from_cal == "BS" and to_cal == "AD":
        converted_year = year - 56
    else:
        raise ValueError(f"Unknown calendar pair: {from_cal} → {to_cal}")

    converted_date = f"{converted_year:04d}-{month:02d}-{day:02d}"


    if style == "iso":
        return converted_date

    month_name = bs_months[month - 1] if to_cal == "BS" else None

    if style == "full":
        if to_cal == "BS":
            return f"{ordinal(day)} {month_name}, {converted_year} BS"
        else:
            import calendar as _cal
            ad_month_name = _cal.month_name[month]
            return f"{ordinal(day)} {ad_month_name}, {converted_year} AD"

    if style == "nepali":
        if to_cal == "BS":
            return f"{day} {month_name} {converted_year} BS"
        else:
            return f"{converted_date} AD"

    return converted_date


customers = [
    {"name": "Ramesh Thapa",  "date": "1985-06-24", "cal": "AD", "need": "BS", "style": "full"},
    {"name": "Sunita Karki",  "date": "2055-09-10", "cal": "BS", "need": "AD", "style": "iso"},
    {"name": "Bikash Rai",    "date": "1998-11-30", "cal": "AD", "need": "BS", "style": "nepali"},
    {"name": "Anjali Gurung", "date": "2040-01-05", "cal": "BS", "need": "AD", "style": "full"},
]

print("=== Bank Date Conversion ===")
for c in customers:
    result = convert_date(c["date"], c["cal"], c["need"], c["style"])
    print(f"{c['name']:<15} | Original: {c['date']} {c['cal']} | Converted: {result}")
print()

"""Question 4 — Word Frequency Counter
A Nepali news website wants to find the most common words in an article to
understand what topics are trending. Write a function that counts how many
times each word appears in a piece of text, then reports the top 3 most
frequent words.
"""

#Prashant Puri

text = """
Nepal is a beautiful country. Nepal has Mount Everest.
Everest is the highest mountain in the world. Many tourists
visit Nepal every year to see Everest and other mountains.
Nepal is known for its mountains and natural beauty.
"""

def word_frequency(text):
    import string

    cleaned = text.translate(str.maketrans("", "", string.punctuation)).lower()
    words = cleaned.split()

    freq = {}
    for word in words:
        freq[word] = freq.get(word, 0) + 1


    top3 = sorted(freq.items(), key=lambda x: (-x[1], x[0]))[:3]
    return top3

print("=== Word Frequency Analysis ===")
print("Top 3 words:")
for word, count in word_frequency(text):
    print(f"{word} — {count} times")
print()

"""Question 5 — Simple ATM Simulator
Build a simple ATM function for a local cooperative bank in Lalitpur. The
function should handle three actions: check balance, deposit, and withdraw.
Each account has a PIN for security. The function should refuse the action if
the PIN is wrong.
"""

accounts = {
    "A001": {"name": "Ramesh Thapa", "balance": 15000, "pin": "1234"},
    "A002": {"name": "Sunita Karki", "balance": 8500,  "pin": "5678"},
    "A003": {"name": "Bikash Rai",   "balance": 22000, "pin": "9012"},
}

def atm(account_id, pin, action, amount=0):
    if account_id not in accounts:
        print("Account not found")
        return

    account = accounts[account_id]

    if account["pin"] != pin:
        print("Incorrect PIN")
        return

    name    = account["name"]
    balance = account["balance"]

    if action == "balance":
        print(f"Account holder: {name} | Balance: NPR {balance}")

    elif action == "deposit":
        account["balance"] += amount
        print(f"NPR {amount} deposited. New balance for {name}: NPR {account['balance']}")

    elif action == "withdraw":
        if amount > balance:
            print("Insufficient funds")
        else:
            account["balance"] -= amount
            print(f"NPR {amount} withdrawn. New balance for {name}: NPR {account['balance']}")

    else:
        print(f"Unknown action: '{action}'. Use 'balance', 'deposit', or 'withdraw'.")


print("=== ATM Simulator ===")
atm("A001", "1234", "balance")
atm("A002", "0000", "withdraw", 2000)
atm("A002", "5678", "deposit",  3000)
atm("A003", "9012", "withdraw", 25000)
atm("A004", "1111", "balance")