# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jC1UoZjnBqrnow9ZdfcPL-MaX5jWL09I

**Week 5 Assignment — Classes and Objects**

Question 1 — Bank Account Manager
A cooperative bank in Lalitpur needs a system to manage customer
accounts. Each account holds a customer's name, account number, and
balance.
Create a class:
class BankAccount:
The class should have:
● __init__ to store name, account_number, and balance (default 0)
● deposit(amount) — adds amount to balance
● withdraw(amount) — deducts amount; print 'Insufficient funds' if
balance is too low
● get_balance() — prints name and current balance
Test with:
accounts = [
("Ramesh Thapa",  "A001", 5000),
("Sunita Karki",  "A002", 0),
("Bikash Rai",    "A003", 12000),
]
Create an object for each. Then: deposit 3000 into A002, withdraw 15000 from
A003 (should fail), withdraw 2000 from A001, and print the final balance of all
three accounts.
"""

#Prashant Puri


class BankAccount:
    def __init__(self, name, account_number, balance=0):
        self.name = name
        self.account_number = account_number
        self.balance = balance

    def deposit(self, amount):
        self.balance += amount

    def withdraw(self, amount):
        if amount > self.balance:
            print(f"Insufficient funds in account {self.account_number}")
        else:
            self.balance -= amount

    def get_balance(self):
        print(f"Name: {self.name}")
        print(f"Account Number: {self.account_number}")
        print(f"Balance: NPR {self.balance}")
        print()


accounts = [
    ("Ramesh Thapa", "A001", 5000),
    ("Sunita Karki", "A002", 0),
    ("Bikash Rai", "A003", 12000),
]

bank_accounts = []

for name, acc_no, balance in accounts:
    bank_accounts.append(BankAccount(name, acc_no, balance))

for account in bank_accounts:
    if account.account_number == "A002":
        account.deposit(3000)

    elif account.account_number == "A003":
        account.withdraw(15000)

    elif account.account_number == "A001":
        account.withdraw(2000)

print("Final Account Balances")
print("----------------------")

for account in bank_accounts:
    account.get_balance()

"""Question 2 — Student Report Card
A school in Bhaktapur records each student's name and their marks in five
subjects. The class should calculate results automatically.
Create a class:
class Student:
The class should have:
● __init__ to store name and a list of marks
● average() — returns the average mark
● grade() — returns A (80+), B (65–79), C (50–64), D (40–49), F (below
40)
● display() — prints name, average, grade, and Pass/Fail (pass =
average 40+)
Test with:
students = [
("Aarav",  [78, 85, 60, 90, 72]),
("Sita",   [45, 50, 38, 60, 55]),
("Bishal", [30, 25, 40, 35, 28]),
("Priya",  [90, 88, 95, 92, 87]),
]
Create an object for each student and call display() on all of them.
"""

#Prashant Puri


class Student:
    def __init__(self, name, marks):
        self.name = name
        self.marks = marks

    def average(self):
        return sum(self.marks) / len(self.marks)

    def grade(self):
        avg = self.average()

        if avg >= 80:
            return "A"
        elif avg >= 65:
            return "B"
        elif avg >= 50:
            return "C"
        elif avg >= 40:
            return "D"
        else:
            return "F"

    def display(self):
        avg = self.average()
        result = "Pass" if avg >= 40 else "Fail"

        print(f"Name: {self.name}")
        print(f"Average: {avg:.2f}")
        print(f"Grade: {self.grade()}")
        print(f"Result: {result}")
        print()


students = [
    ("Aarav", [78, 85, 60, 90, 72]),
    ("Sita", [45, 50, 38, 60, 55]),
    ("Bishal", [30, 25, 40, 35, 28]),
    ("Priya", [90, 88, 95, 92, 87]),
]

student_objects = []

for name, marks in students:
    student_objects.append(Student(name, marks))

for student in student_objects:
    student.display()

"""Question 3 — Food Delivery App  
A food delivery app in Kathmandu has three types of delivery partners: bike
riders, walkers, and car drivers. All three are delivery partners but each
calculates earnings differently.
Create a parent class:
class DeliveryPartner:
def __init__(self, name, partner_id, deliveries):
def total_earning(self):    # to be overridden
def display(self):          
# prints name, deliveries, and total earning
Create three child classes:
class BikeRider(DeliveryPartner):
● __init__ also takes km_travelled
● total_earning() — NPR 80 per delivery + NPR 5 per km
class Walker(DeliveryPartner):
● __init__ also takes rainy_deliveries
● total_earning() — NPR 60 per delivery + NPR 50 per rainy delivery
class CarDriver(DeliveryPartner):
● __init__ also takes fuel_cost
● total_earning() — NPR 120 per delivery − fuel cost
Test with:
partners = [
BikeRider("Santosh Rai",  "B-01", 15, 42),
Walker("Kabita Maharjan", "W-01", 18, 5),
CarDriver("Roshan KC",    "C-01", 20, 850),
]
Call display() on all partners using a loop. Then print the partner with the
highest earning.
"""

#Prashant Puri


class DeliveryPartner:
    def __init__(self, name, partner_id, deliveries):
        self.name = name
        self.partner_id = partner_id
        self.deliveries = deliveries

    def total_earning(self):
        return 0

    def display(self):
        print(f"Name: {self.name}")
        print(f"Partner ID: {self.partner_id}")
        print(f"Deliveries: {self.deliveries}")
        print(f"Total Earning: NPR {self.total_earning()}")
        print()


class BikeRider(DeliveryPartner):
    def __init__(self, name, partner_id, deliveries, km_travelled):
        super().__init__(name, partner_id, deliveries)
        self.km_travelled = km_travelled

    def total_earning(self):
        return (self.deliveries * 80) + (self.km_travelled * 5)


class Walker(DeliveryPartner):
    def __init__(self, name, partner_id, deliveries, rainy_deliveries):
        super().__init__(name, partner_id, deliveries)
        self.rainy_deliveries = rainy_deliveries

    def total_earning(self):
        return (self.deliveries * 60) + (self.rainy_deliveries * 50)


class CarDriver(DeliveryPartner):
    def __init__(self, name, partner_id, deliveries, fuel_cost):
        super().__init__(name, partner_id, deliveries)
        self.fuel_cost = fuel_cost

    def total_earning(self):
        return (self.deliveries * 120) - self.fuel_cost


partners = [
    BikeRider("Santosh Rai", "B-01", 15, 42),
    Walker("Kabita Maharjan", "W-01", 18, 5),
    CarDriver("Roshan KC", "C-01", 20, 850),
]

print("Partner Details")
print("----------------")

for partner in partners:
    partner.display()

highest = partners[0]

for partner in partners:
    if partner.total_earning() > highest.total_earning():
        highest = partner

print("Highest Earning Partner")
print("-----------------------")
print(f"Name: {highest.name}")
print(f"Earning: NPR {highest.total_earning()}")

"""Question 4 — Bus Ticket Booking (Sajha Yatayat)
Sajha Yatayat buses run between Kathmandu and Pokhara. Each bus has a
route, total seats, and a list of booked seats. Customers book by seat number.
Create a class:
class Bus:
The class should have:
● __init__ to store route, total_seats, and an empty booked list
● book_seat(seat_number, passenger_name) — adds the booking if seat
is available; print 'Seat already booked' if not
● available_seats() — returns count of remaining seats
● passenger_list() — prints all booked seats and passenger names
Test with:
bus = Bus("Kathmandu - Pokhara", 10)
Book these in order:
bookings = [
(3, "Ramila Shrestha"),
(7, "Deepak Gurung"),
(3, "Anita Rai"),        
# duplicate
(1, "Prakash Magar"),
(7, "Suman Tamang"),     # duplicate
]
After all bookings, print available seats and the full passenger list.
"""

#Prashant Puri

class Bus:
    def __init__(self, route, total_seats):
        self.route = route
        self.total_seats = total_seats
        self.booked_seats = {}

    def book_seat(self, seat_number, passenger_name):
        if seat_number in self.booked_seats:
            print("Seat already booked")
        else:
            self.booked_seats[seat_number] = passenger_name
            print(f"Seat {seat_number} booked for {passenger_name}")

    def available_seats(self):
        return self.total_seats - len(self.booked_seats)

    def passenger_list(self):
        print("\nPassenger List")
        print("--------------")

        for seat, passenger in sorted(self.booked_seats.items()):
            print(f"Seat {seat}: {passenger}")


bus = Bus("Kathmandu - Pokhara", 10)

bookings = [
    (3, "Ramila Shrestha"),
    (7, "Deepak Gurung"),
    (3, "Anita Rai"),
    (1, "Prakash Magar"),
    (7, "Suman Tamang"),
]

for seat, passenger in bookings:
    bus.book_seat(seat, passenger)

print("\nAvailable Seats:", bus.available_seats())

bus.passenger_list()