# -*- coding: utf-8 -*-
"""Week 3

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SANQjwd6vQDcxAvybbQFZvFukLkpPVSq

Week 3 Assignment

Question 1 — ATM Withdrawal Validator (Conditionals)
Scenario: A Nepali bank ATM allows customers to withdraw money under the following rules:

The withdrawal amount must be a multiple of NPR 500.

The withdrawal amount must not exceed the account balance.

The daily withdrawal limit is NPR 50,000.

Task: Write a program that takes the following inputs:

balance — current account balance

daily_withdrawn — total amount already withdrawn today

amount — amount the customer wants to withdraw

Print appropriate messages such as:

"Withdrawal successful."

"Invalid amount. Must be a multiple of NPR 500."

"Insufficient balance."

"Daily withdrawal limit reached."

"Your current balance after withdrawal: NPR XXXX"
"""

#Prashant Puri

balance = int(input("Enter your account balance: "))
daily_withdrawn = int(input("Enter amount already withdrawn today: "))
amount = int(input("Enter withdrawal amount: "))

if amount % 500 != 0:
    print("Invalid amount. Must be a multiple of NPR 500.")

elif amount > balance:
    print("Insufficient balance.")

elif daily_withdrawn + amount > 50000:
    print("Daily withdrawal limit reached.")

else:
    balance = balance - amount
    print("Withdrawal successful.")
    print("Your current balance after withdrawal: NPR", balance)

"""Question 2 — Online Store Discount System (Conditionals)
Scenario: An online shopping platform in Nepal provides discounts according to purchase amount.

Total Purchase (NPR)

Discount

Less than NPR 1,000

No discount

NPR 1,000 – NPR 4,999

5%

NPR 5,000 – NPR 14,999

10%

NPR 15,000 and above

20%

Additionally, loyalty members receive an extra 5% discount on the discounted amount.

Task: Write a program that calculates the final payable amount after applying all discounts.
"""

#Prashant Puri
purchase = float(input("Enter total purchase amount: "))

member = input("Are you a loyalty member? (yes/no): ")

discount = 0

if purchase < 1000:
    discount = 0

elif purchase >= 1000 and purchase <= 4999:
    discount = 5

elif purchase >= 5000 and purchase <= 14999:
    discount = 10
else:
    discount = 20

discount_amount = (purchase * discount) / 100
final_amount = purchase - discount_amount

if member == "yes":
    extra_discount = (final_amount * 5) / 100
    final_amount = final_amount - extra_discount

print("Final payable amount: NPR", final_amount)

"""Question 3 — Inventory Restock Alert (Loop + Conditional)
Scenario: A grocery store in Kathmandu tracks inventory for daily operations.

If an item's stock falls below the threshold level, it should trigger a restock alert.

Task: Loop through the inventory list and print restock alerts. At the end, display the total number of items that need restocking.


inventory = [
    {"item": "Rice", "stock": 5, "threshold": 10},
    {"item": "Eggs", "stock": 24, "threshold": 12},
    {"item": "Milk", "stock": 3, "threshold": 6},
    {"item": "Bread", "stock": 8, "threshold": 5},
    {"item": "Chicken", "stock": 0, "threshold": 4},
    {"item": "Cooking Oil", "stock": 2, "threshold": 3},
]
"""

#Prashant Puri

inventory = [
    {"item": "Rice", "stock": 5, "threshold": 10},
    {"item": "Eggs", "stock": 24, "threshold": 12},
    {"item": "Milk", "stock": 3, "threshold": 6},
    {"item": "Bread", "stock": 8, "threshold": 5},
    {"item": "Chicken", "stock": 0, "threshold": 4},
    {"item": "Cooking Oil", "stock": 2, "threshold": 3},
]

restock_count = 0

for item in inventory:

    if item["stock"] < item["threshold"]:

        print(item["item"], "- Restock Needed")

        restock_count = restock_count + 1

print("Total items needing restock:", restock_count)

"""Question 4 — Password Strength Checker (Loop + Conditional)
A website requires users to create strong passwords for account security.

At least 8 characters long

Contains at least one uppercase letter

Contains at least one lowercase letter

Contains at least one digit

Contains at least one special character from !@#$%^&*

Write a program that checks whether passwords are strong or weak and prints missing criteria.


passwords = ["hello", "Hello123", "H3ll0@World", "12345678", "MyP@ss!"]
"""

#Prashant Puri
passwords = ["hello", "Hello123", "H3ll0@World", "12345678", "MyP@ss!"]

special_characters = "!@#$%^&*"

for password in passwords:

    print("\nChecking Password:", password)

    has_upper = False
    has_lower = False
    has_digit = False
    has_special = False

    if len(password) >= 8:
        length_ok = True
    else:
        length_ok = False

    for ch in password:

        if ch.isupper():
            has_upper = True

        elif ch.islower():
            has_lower = True

        elif ch.isdigit():
            has_digit = True

        elif ch in special_characters:
            has_special = True

    if length_ok and has_upper and has_lower and has_digit and has_special:
        print("Strong Password")

    else:
        print("Weak Password")

        if not length_ok:
            print("- Must contain at least 8 characters")

        if not has_upper:
            print("- Missing uppercase letter")

        if not has_lower:
            print("- Missing lowercase letter")

        if not has_digit:
            print("- Missing digit")

        if not has_special:
            print("- Missing special character")

"""Question 5 — Taxi Fare Calculator (Conditionals + Loop)
Scenario: A taxi service operating in Kathmandu calculates fares using the following structure.

Fare Rule

Rate

Base fare (first 2 km)

NPR 150

Next 8 km (km 3–10)

NPR 35 per km

Beyond 10 km

NPR 28 per km

Night surcharge (10 PM – 5 AM)

Additional 10%

Write a program that calculates taxi fare for each trip based on distance and travel time.


trips = [
    {"distance": 1.5, "hour": 14},
    {"distance": 5.0, "hour": 22},
    {"distance": 12.0, "hour": 3},
    {"distance": 8.5, "hour": 10},
    {"distance": 2.0, "hour": 23},
]

"""

trips = [
    {"distance": 1.5, "hour": 14},
    {"distance": 5.0, "hour": 22},
    {"distance": 12.0, "hour": 3},
    {"distance": 8.5, "hour": 10},
    {"distance": 2.0, "hour": 23},
]

for trip in trips:

    distance = trip["distance"]
    hour = trip["hour"]

    fare = 0

    if distance <= 2:

        fare = 150

    elif distance <= 10:

        fare = 150 + (distance - 2) * 35

    else:

        fare = 150 + (8 * 35) + (distance - 10) * 28

    if hour >= 22 or hour <= 5:

        fare = fare + (fare * 10 / 100)

    print("Distance:", distance, "km")
    print("Travel Hour:", hour)
    print("Total Fare: NPR", fare)
    print()