# -*- coding: utf-8 -*-
"""Week 6

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uxaezVy49VVa9TZ-3SDHISe8ukFoa-JP
"""

#Question 1 — Temperature Logger (math module)

#Prashant Puri

import math

# Global variable
station_name = "Kathmandu Weather Station"

temperatures = [18.4, 22.1, 15.7, 29.3, 11.8, 25.6, 19.2]

# Function to calculate average
def get_average(temps):
    return sum(temps) / len(temps)

# Function to calculate standard deviation
def get_deviation(temps):
    mean = get_average(temps)   # Local variable
    variance = sum((x - mean) ** 2 for x in temps) / len(temps)
    return math.sqrt(variance)

# Function to print summary
def get_summary(temps):
    print("Station Name:", station_name)
    print("Minimum Temperature:", min(temps))
    print("Maximum Temperature:", max(temps))
    print("Average Temperature:", get_average(temps))
    print("Standard Deviation:", get_deviation(temps))

# Call function
get_summary(temperatures)

# print(mean)
# This will cause NameError because 'mean' is a local variable
# inside get_deviation() and cannot be accessed outside.

#Question 2 — Bill Splitter (random module)

#Prashant Puri

import random

random.seed(42)

friends = ["Ramesh", "Sunita", "Bikash", "Anjali", "Dipak"]
total_bill = 3750

# Function to split bill equally
def split_bill(friends, total):
    return total / len(friends)

# Function to pick lucky person
def pick_lucky(friends):
    return random.choice(friends)

# Final summary function
def final_summary(friends, total):
    share = split_bill(friends, total)
    lucky_person = pick_lucky(friends)

    print("Each person pays:", share)

    for person in friends:
        if person == lucky_person:
            lucky_total = share + 50   # Local variable
            print(person, "is lucky and pays:", lucky_total)
        else:
            print(person, "pays:", share)

# Call function
final_summary(friends, total_bill)

#Question 3 — Exam Scheduler (datetime module)

#Prashant Puri
import datetime

# Global variable
college_name = "Bhaktapur Multiple Campus"

start_date = "2025-05-01"

exams = [
    ("Python Programming", 0),
    ("Data Structures", 3),
    ("Database Systems", 6),
    ("Computer Networks", 10),
    ("Mathematics", 14),
]

# Function to parse date
def parse_date(date_str):
    return datetime.datetime.strptime(date_str, "%Y-%m-%d")

# Function to calculate exam date
def get_exam_date(start_str, days):
    start = parse_date(start_str)
    exam_date = start + datetime.timedelta(days=days)
    return exam_date.strftime("%Y-%m-%d")

# Function to print schedule
def print_schedule(start_str, exams):
    print(college_name)
    print("Exam Schedule")

    for subject, days in exams:
        print(subject, ":", get_exam_date(start_str, days))

# Call function
print_schedule(start_date, exams)

#Question 4 — Shopping Discount (own module)

#Prashant Puri

# Global constant
TAX_RATE = 0.13

# Function to apply discount
def apply_discount(price, percent):
    return price - (price * percent / 100)

# Function to apply tax
def apply_tax(price):
    return price + (price * TAX_RATE)

# Function to calculate final price
def final_price(price, discount_pct):
    discounted_price = apply_discount(price, discount_pct)
    return apply_tax(discounted_price)

    from discount import final_price, TAX_RATE

products = [
    ("Laptop", 85000, 10),
    ("Headphones", 4500, 15),
    ("Phone Case", 800, 5),
    ("USB Cable", 600, 0),
]

print("Tax Rate:", TAX_RATE)

for name, price, discount in products:
    final = final_price(price, discount)
    print("Product:", name)
    print("Original Price:", price)
    print("Final Price:", final)
    print("-------------------")

